{% set name = "PolyRound" %}
{% set version = "0.2.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/PolyRound-{{ version }}.tar.gz
  sha256: 98c8c276fc3a5492a0403fb3bd998c0d71e1ec5ca847452c11dfb93da4bd1f96

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy >=1.2
    - pandas >=1.2
    - python-dateutil >=2.8
    - python-libsbml >=5.18
    - scipy >=1.4
    - optlang >=1.4
    - cobra >=0.20

test:
  imports:
    - PolyRound
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.com/csb.ethz/PolyRound
  summary: A python package for rounding polytopes.
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Theorell
